version: "3.8"

services:

  database:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  app:
    build:
      context: ./bookstore
      target: development
    depends_on:
      - database
    volumes:
      - ./bookstore:/app/
    ports:
      - "8000:8000"
