# Generated by Django 4.0.1 on 2022-01-05 23:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('pages', models.IntegerField()),
                ('author', models.CharField(max_length=255)),
            ],
        ),
    ]
