# Generated by Django 4.0.1 on 2022-01-06 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_separate_authors_from_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
    ]
