# Generated by Django 4.0.1 on 2022-01-06 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_book_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author_foreign_key',
            new_name='author',
        ),
    ]
